services:
  - type: web
    name: weather-dashboard
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: WEATHER_API_KEY
        sync: false   # you'll set actual value in Render dashboard
